wx:
  secret: 661e82bcf46dbe6c203c9f2f91d8937d
  appId: wx15d4269d3210863d
  mchId:
  paySignKey:
  certName: /cert/apiclient_cert.p12
  getCode: https://open.weixin.qq.com/connect/oauth2/authorize?appid=%s&redirect_uri=%s&response_type=code&scope=%s&state=STAT#wechat_redirect
  notifyUrl: http://localhost:8085/api/pay/notify
  orderQuery: https://api.mch.weixin.qq.com/pay/orderquery
  refundUrl: https://api.mch.weixin.qq.com/secapi/pay/refund
  refundQueryUrl: https://api.mch.weixin.qq.com/pay/refundquery
  tradeType: JSAPI
  uniformOrder: https://api.mch.weixin.qq.com/pay/unifiedorder
  userMessage: https://api.weixin.qq.com/sns/userinfo?access_token=%s&openid=%s&lang=zh_CN
  webAccessTokenHttps: https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code
  templateId: nAt_DYLLwYXkIhtDb5nyEm0ynrt98OK3Z3MmeUooPz4