#spring
spring:
  application:
    name: new-worth
  profiles:
    active: local
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8087

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  typeAliasesPackage: cn.worth.**.domain
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true

#Redis 缓存时长
redis:
  cache:
    expiration: 3600

swagger:
  authorization:
    key-name: Authorization
  title: 后台管理系统接口文档
  base-package: cn.worth
  exclude-path: /error, /ops/**
  description: 登录接口 /ppdk-api/oauth/token?username=admin&password=123456&randomStr=37811532935365145&code=5nge&grant_type=password&scope=server， 请求头加Authorization; Basic d286Z29uZ2Rhbg==
