spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.31.55.134:3306/new-worth?useUnicode=true&characterEncoding=utf8&&useSSL=false
    username: root
    password: 1234
  cache:
    type: redis
  redis:
    database: 0 #Redis数据库索引（默认为0）
    host: 118.31.55.134 #Redis服务器地址
    port: 6379 #Redis服务器连接端口
    password:
    timeout: 3600 #连接超时时间（毫秒）
#    lettuce:
#      pool:
#        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 8 #连接池中的最大空闲连接
#        min-idle: 0 #连接池中的最小空闲连接

ignore:
  urls:
    - /oauth/**
    - /swagger-resources/**
    - /swagger-ui.html
    - /v2/api-docs
    - /swagger/api-docs
    - /webjars/**
    - /file/download
    - /druid/**

logging:
  #  path: C:/logs
  level:
    com.baomidou: debug
    org.springframework.web: error
    org.springframework.security: DEBUG
    cn.worth: DEBUG
#    org.quartz: DEBUG

#worth:
#  uploadPath: /Users/myireland # nw-file 使用